### ISSUE TITLE
Přestal fungovat kodi přes befun

### ISSUE THREAD

**Issue by Oldamaly** [kodi-czsk/plugin.video.befun.cz#2]
Dobrý den, někdy od včerejšího dne přestaly fungovat doplňky k přehrávání videa přes befun.cz, který využívá streamuj.tv a sosac.
Při pokusu o přehrávání se zobrazí hláška, že jde o nepodporovaný přehrávač. Je možné toto prosím nějak řešit?
Děkuji

**Comment by lzoubek** [comment]
Opět v provozu
